{% set version="0.2.1" %}
{% set name="ichorCNA" %}

package:
  name: 'r-{{ name|lower }}'
  version: '{{ version }}'

source:
  url: https://github.com/quevedor2/ichorCNA/archive/v{{ version }}.tar.gz
  sha256: 2c16d252783fffb1a39b36a582d5065ae62f42ab4a12123b67916033598c28b9

build:
  number: 2
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  host:
    - r-base
    - perl  # for adding in correct path references to scripts
    - 'bioconductor-genomeinfodb >=1.8.7'
    - 'bioconductor-hmmcopy >=1.14.0'
    - r-optparse
    - r-plyr
  run:
    - r-base
    - 'bioconductor-genomeinfodb >=1.8.7'
    - 'bioconductor-hmmcopy >=1.14.0'
    - r-optparse
    - r-plyr

test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
    - runIchorCNA.R -h 2>&1 | grep Usage
    - createPanelOfNormals.R -h 2>&1 | grep Usage

about:
  home: https://github.com/broadinstitute/ichorCNA
  license: GPL-3
  license_file: LICENSE
  summary:  Master build of broadinstitute/ichorCNA (commit: 5bfc03e) Estimating tumor fraction in cell-free DNA from ultra-low-pass whole genome sequencing.
